name: 프론트엔드 배포

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          npm install
          # 또는 yarn install

      - name: React 앱 빌드
        run: |
          npm run build
          # 또는 yarn build

      - name: 서버로 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # GluveFront 폴더 확인 후 없으면 생성
            if [ ! -d "/GluveFront/build" ]; then
              sudo mkdir -p /GluveFront/build
            fi
            
            cd /GluveFront || exit
            
            # 빌드된 작업물만 복사
            rsync -r --delete-after build/ /GluveFront/build/

