name: 프론트엔드 배포

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          npm install
          # 또는 yarn install

      - name: React 앱 빌드
        run: |
          npm run build
          # 또는 yarn build

      - name: 서버로 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
        
            
            cd /GluveFront || exit
            
            # Check if the directory is a Git repository before attempting to pull
            if [ -d .git ]; then
              git pull origin main
            else
              # If not a Git repository, initialize a new one and set up tracking
              git init
              git remote add origin <repository-url>
              git fetch origin main
              git checkout -b main --track origin/main
            fi
            
            # 빌드된 작업물만 복사
            rsync -r --delete-after ./build/ /GluveFront/build/
